# Generated by Django 5.2.12 on 2026-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_refine_gather_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipientaddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("tron", "Tron")],
                help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Tron: Tron",
                verbose_name="地址格式",
            ),
        ),
    ]
