# Generated by Django 5.2.12 on 2026-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0005_deposit_risk_level_deposit_risk_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositaddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("tron", "Tron")], verbose_name="链类型"
            ),
        ),
    ]
