# Generated by Django 5.2.12 on 2026-05-15 01:29

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0008_alter_onchaintransfer_confirm_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="create2_factory_address",
            field=common.fields.EvmAddressField(
                blank=True,
                db_index=True,
                max_length=42,
                null=True,
                verbose_name="CREATE2 工厂合约地址",
            ),
        ),
        migrations.AlterField(
            model_name="broadcasttask",
            name="transfer_type",
            field=models.CharField(
                choices=[
                    ("iv", "💳 支付"),
                    ("deposit", "💰 充币"),
                    ("withdrawal", "🏧 提币"),
                    ("gas-recharge", "⛽ Gas分发"),
                    ("deposit-collection", "💵 归集充币"),
                    ("prefunding", "🏦 注入金库资金"),
                    ("x402_facilitate", "x402 代付"),
                    ("contract_deploy_collect", "合约部署归集"),
                ],
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="onchaintransfer",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("iv", "💳 支付"),
                    ("deposit", "💰 充币"),
                    ("withdrawal", "🏧 提币"),
                    ("gas-recharge", "⛽ Gas分发"),
                    ("deposit-collection", "💵 归集充币"),
                    ("prefunding", "🏦 注入金库资金"),
                    ("x402_facilitate", "x402 代付"),
                    ("contract_deploy_collect", "合约部署归集"),
                ],
                default="",
                verbose_name="类型",
            ),
        ),
    ]
