# Generated by Django 5.2.12 on 2026-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evm", "0005_contractdeploycollection_x402facilitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractdeploycollection",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rpc_rejected", "节点拒绝"),
                    ("insufficient_balance", "余额不足"),
                    ("fee_too_low", "手续费过低"),
                    ("execution_reverted", "链上执行回退"),
                    ("expected_transfer_missing", "链上执行成功但预期资产移动缺失"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="x402facilitation",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rpc_rejected", "节点拒绝"),
                    ("insufficient_balance", "余额不足"),
                    ("fee_too_low", "手续费过低"),
                    ("execution_reverted", "链上执行回退"),
                    ("expected_transfer_missing", "链上执行成功但预期资产移动缺失"),
                ],
                default="",
                max_length=64,
                verbose_name="失败原因",
            ),
        ),
    ]
