# Generated by Django 5.2.12 on 2026-05-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evm", "0007_evm_idempotency_constraints"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractdeploycollection",
            old_name="vault_address",
            new_name="recipient_address",
        ),
    ]
